Update setup.cfg to be compliant with setuptools v78.0.0
Version 78.0.0 of `setuptools` no longer support dash in keys, they should be updated to use underscore (there has been a deprecation warning since 3 Mar 2021).
https://setuptools.pypa.io/en/stable/history.html#v78-0-0

Keys with dashes fail like this:
```
setuptools.errors.InvalidConfigError: Invalid dash-separated key 
'description-file' in 'metadata' (setup.cfg), please use the underscore name 
'description_file' instead.
```

Though the `setuptools` change was rolled in v78.0.2 one day later, it will be reintroduced in 2026, so this patch will make `django-pkgconf` compliant.